2025-03-03 11:44:23.296 | WARNING  | etl.validators.schema_validator:_load_schemas:32 - Schemas directory /Users/juliusrechenbach/API ProHandelTest/etl/validators/schemas does not exist
2025-03-03 11:44:23.750 | INFO     | lambda_function:lambda_handler:41 - Received event: {"request": {"operation": "test"}}
2025-03-03 11:44:23.750 | INFO     | etl.connectors.prohandel_connector:get_entity_list:106 - Fetching article data (page 1, pagesize 1)
2025-03-03 11:44:23.750 | INFO     | etl.utils.auth:authenticate:42 - Authenticating with ProHandel API...
2025-03-03 11:44:24.003 | ERROR    | etl.utils.auth:authenticate:56 - Authentication failed: 404 Client Error: Not Found for url: https://linde.prohandel.de/api/v2/auth/token
2025-03-03 11:44:24.003 | ERROR    | etl.utils.auth:authenticate:58 - Response status: 404
2025-03-03 11:44:26.004 | INFO     | etl.utils.auth:authenticate:42 - Authenticating with ProHandel API...
2025-03-03 11:44:26.101 | ERROR    | etl.utils.auth:authenticate:56 - Authentication failed: 404 Client Error: Not Found for url: https://linde.prohandel.de/api/v2/auth/token
2025-03-03 11:44:26.101 | ERROR    | etl.utils.auth:authenticate:58 - Response status: 404
2025-03-03 11:44:28.104 | INFO     | etl.utils.auth:authenticate:42 - Authenticating with ProHandel API...
2025-03-03 11:44:28.207 | ERROR    | etl.utils.auth:authenticate:56 - Authentication failed: 404 Client Error: Not Found for url: https://linde.prohandel.de/api/v2/auth/token
2025-03-03 11:44:28.207 | ERROR    | etl.utils.auth:authenticate:58 - Response status: 404
2025-03-03 11:44:28.207 | ERROR    | etl.connectors.prohandel_connector:get_entity_list:121 - Error fetching article data: RetryError[<Future at 0x10a0fa450 state=finished raised HTTPError>]
